# %APPDATA%\alacritty\alacritty.toml

# Setup for running WSL
# [terminal]
# [terminal.shell]
# args = ["--cd ~"]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = false
dynamic_padding = true
opacity = 0.98
padding = { x = 8, y = 6 }

[font]
normal = { family = "Geist Mono", style = "Regular" }
bold = { family = "Geist Mono", style = "Bold" }
italic = { family = "Geist Mono", style = "Italic" }
size = 10.5
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },

  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },

  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward" },

  { key = "K", mods = "Control|Shift", action = "ClearHistory" },
  { key = "L", mods = "Control", chars = "\f" },
]
